version: '3'
services:
  redis:
    image: redis
    container_name: kafka-redis
    ports:
      - 6379:6379
    #    volumes:
    #      - ./redis.conf:/etc/redis/redis.conf
    #      - ./data:/data
    command: redis-server /etc/redis/redis.conf
    privileged: true

#docker-compose -f docker-compose-single.yml up -d
